#!/usr/bin/env python3

import argparse
from pathlib import Path

DEFAULT_UNICODE_VERSION = "15.1.0"


def parse_properties(path):
    properties = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, property_name = [part.strip() for part in line.split(";", 1)]
        if ".." in codepoints:
            first, last = codepoints.split("..", 1)
        else:
            first = last = codepoints
        properties.setdefault(property_name, []).append((int(first, 16), int(last, 16)))
    return properties


def merge_ranges(ranges):
    result = []
    for first, last in sorted(ranges):
        if result and first <= result[-1][1] + 1:
            result[-1] = (result[-1][0], max(result[-1][1], last))
        else:
            result.append((first, last))
    return result


def combine(properties, names):
    return merge_ranges([item for name in names for item in properties[name]])


def render_table(name, ranges):
    lines = [f"static constexpr FTSUnicodeRange {name}[] = {{"]
    lines.extend(f"    {{0x{first:06X}, 0x{last:06X}}}," for first, last in ranges)
    lines.append("};")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate FTS Unicode property tables")
    parser.add_argument(
        "--unicode-version",
        default=DEFAULT_UNICODE_VERSION,
        help="Unicode version recorded in the generated header",
    )
    parser.add_argument("ucd_dir", type=Path, help="Unicode Character Database root")
    parser.add_argument("output", type=Path, help="Generated C++ header")
    args = parser.parse_args()

    scripts = parse_properties(args.ucd_dir / "Scripts.txt")
    derived_core = parse_properties(args.ucd_dir / "DerivedCoreProperties.txt")
    property_list = parse_properties(args.ucd_dir / "PropList.txt")
    emoji = parse_properties(args.ucd_dir / "emoji" / "emoji-data.txt")
    categories = parse_properties(
        args.ucd_dir / "extracted" / "DerivedGeneralCategory.txt"
    )

    tables = {
        "FTS_UNICODE_HAN_RANGES": scripts["Han"],
        "FTS_UNICODE_HIRAGANA_RANGES": scripts["Hiragana"],
        "FTS_UNICODE_KATAKANA_RANGES": scripts["Katakana"],
        "FTS_UNICODE_ALPHABETIC_RANGES": derived_core["Alphabetic"],
        "FTS_UNICODE_DECIMAL_NUMBER_RANGES": categories["Nd"],
        "FTS_UNICODE_WHITESPACE_RANGES": property_list["White_Space"],
        "FTS_UNICODE_PUNCTUATION_RANGES": combine(
            categories, ["Pc", "Pd", "Pe", "Pf", "Pi", "Po", "Ps"]
        ),
        "FTS_UNICODE_COMBINING_MARK_RANGES": combine(categories, ["Mc", "Me", "Mn"]),
        "FTS_UNICODE_EMOJI_RANGES": combine(
            emoji, ["Emoji_Presentation", "Extended_Pictographic"]
        ),
    }

    content = "\n".join(
        [
            f"// Generated by scripts/generate_unicode_tables.py from Unicode {args.unicode_version}.",
            "// See https://www.unicode.org/terms_of_use.html.",
            "#pragma once",
            "",
            "#include <cstdint>",
            "",
            "// clang-format off",
            "",
            "namespace duckdb {",
            "",
            "struct FTSUnicodeRange {",
            "  int32_t first;",
            "  int32_t last;",
            "};",
            "",
            "\n\n".join(
                render_table(name, merge_ranges(ranges))
                for name, ranges in tables.items()
            ),
            "",
            "} // namespace duckdb",
            "",
            "// clang-format on",
            "",
        ]
    )
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
